In [1]:
import sqlite3
import pandas as pd
import numpy as np

In [2]:
con = sqlite3.connect("covid.sqlite")
cur = con.cursor()

cases_df = pd.read_sql_query("SELECT * FROM cases WHERE date >= DATE('now','-31 day') ORDER BY date DESC", con)

In [3]:
cases_df = cases_df.rename(columns={'cases_per_100k_7_day_count' : 'cases','percent_test_results_reported':'test_percent','community_transmission_level' : 'severity'  })

In [4]:
cases_df.head()

,index,state_name,county_name,fips_code,date,cases,test_percent,severity
0,2469562,Texas,Wise County,48497,2022-03-07T00:00:00.000,45.725,None,moderate
1,2469563,Virginia,Greene County,51079,2022-03-07T00:00:00.000,166.507,None,high
2,2469564,Virginia,Albemarle County,51003,2022-03-07T00:00:00.000,160.066,None,high
3,2469565,California,Siskiyou County,06093,2022-03-07T00:00:00.000,110.246,None,high
4,2469566,Kentucky,Trimble County,21223,2022-03-07T00:00:00.000,118.050,None,high

In [5]:
cases_df.tail()

,index,state_name,county_name,fips_code,date,cases,test_percent,severity
96655,1306022,Nebraska,Garden County,31069,2022-02-06T00:00:00.000,0.000,None,high
96656,1306023,Nebraska,Grant County,31075,2022-02-06T00:00:00.000,0.000,None,None
96657,1306024,Georgia,Macon County,13193,2022-02-06T00:00:00.000,393.914,35.71429,high
96658,1306025,Maine,Piscataquis County,23021,2022-02-06T00:00:00.000,327.674,18.99642,high
96659,1306026,South Dakota,Brule County,46015,2022-02-06T00:00:00.000,434.208,20.0,high

In [6]:
#change suppressed to zero
cases_df.loc[cases_df.cases == "suppressed",'cases'] = "0"
#remove commas
cases_df.cases = cases_df.cases.apply(lambda x: x.replace(',',''))
#now cases can be converted to a numeric data type
cases_df.cases = cases_df.cases.astype(float)
cases_df = cases_df.sort_values(by = ['cases'])

In [7]:
cases_df.head()

,index,state_name,county_name,fips_code,date,cases,test_percent,severity
32805,2014824,Nebraska,Chase County,31029,2022-02-25T00:00:00.000,0.0,4.34783,low
61055,2258662,Nebraska,Franklin County,31061,2022-02-17T00:00:00.000,0.0,None,None
11728,1771746,Kansas,Elk County,20049,2022-03-04T00:00:00.000,0.0,None,low
11729,1771747,Kansas,Clark County,20025,2022-03-04T00:00:00.000,0.0,None,high
22373,2480146,Kansas,Rooks County,20163,2022-03-01T00:00:00.000,0.0,0.0,high

In [8]:
cases_df.tail()

,index,state_name,county_name,fips_code,date,cases,test_percent,severity
56337,1761593,South Dakota,Dewey County,46041,2022-02-18T00:00:00.000,11710.794,14.28571,high
88152,2456387,Texas,Loving County,48301,2022-02-08T00:00:00.000,11834.320,36.0,high
85968,1552795,Texas,Loving County,48301,2022-02-09T00:00:00.000,11834.320,40.0,high
91292,1307096,Texas,Loving County,48301,2022-02-07T00:00:00.000,14201.183,44.11765,high
94592,1303959,Texas,Loving County,48301,2022-02-06T00:00:00.000,15976.331,40.0,high

In [9]:
cases_df = cases_df.sort_values(by = ['test_percent'])

In [10]:
cases_df.head()

,index,state_name,county_name,fips_code,date,cases,test_percent,severity
67665,855,Texas,Cottle County,48101,2022-02-14T00:00:00.000,0.0,0.0,low
44763,1321751,Illinois,Putnam County,17155,2022-02-22T00:00:00.000,0.0,0.0,low
23739,1323279,Oklahoma,Beaver County,40007,2022-02-28T00:00:00.000,0.0,0.0,moderate
51593,2461693,Alaska,Denali Borough,02068,2022-02-19T00:00:00.000,0.0,0.0,high
20765,2478538,Kansas,Stanton County,20187,2022-03-01T00:00:00.000,0.0,0.0,low

In [11]:
cases_df.tail()

,index,state_name,county_name,fips_code,date,cases,test_percent,severity
5332,1562352,Vermont,Addison County,50001,2022-03-06T00:00:00.000,3064.415,None,high
436,2469998,Vermont,Orleans County,50019,2022-03-07T00:00:00.000,3521.101,None,high
5716,1562736,Vermont,Orleans County,50019,2022-03-06T00:00:00.000,3569.183,None,high
5011,1562031,Vermont,Orange County,50017,2022-03-06T00:00:00.000,5229.821,None,high
1293,2470855,Vermont,Orange County,50017,2022-03-07T00:00:00.000,5254.050,None,high

In [12]:
#change None to zero
cases_df.test_percent.fillna("0", inplace = True)
#remove commas
cases_df.test_percent = cases_df.test_percent.apply(lambda x: x.replace(',',''))
#now test percent can be converted to a numeric data type
cases_df.test_percent = cases_df.test_percent.astype(float)
cases_df = cases_df.sort_values(by = ['test_percent'])

In [13]:
cases_df.head()

,index,state_name,county_name,fips_code,date,cases,test_percent,severity
67665,855,Texas,Cottle County,48101,2022-02-14T00:00:00.000,0.0,0.0,low
87484,2455719,Montana,Carter County,30011,2022-02-08T00:00:00.000,0.0,0.0,high
2318,2471880,Alabama,Marengo County,01091,2022-03-07T00:00:00.000,0.0,0.0,moderate
2276,2471838,Texas,Schleicher County,48413,2022-03-07T00:00:00.000,0.0,0.0,low
27850,2475967,South Dakota,Jerauld County,46073,2022-02-27T00:00:00.000,0.0,0.0,high

In [14]:
cases_df.tail()

,index,state_name,county_name,fips_code,date,cases,test_percent,severity
8456,2499062,Iowa,Jefferson County,19101,2022-03-05T00:00:00.000,87.456,100.0,high
24913,1324453,Iowa,Lee County,19111,2022-02-28T00:00:00.000,106.961,100.0,high
27711,2475828,Iowa,Guthrie County,19077,2022-02-27T00:00:00.000,93.554,100.0,high
9152,2499758,Iowa,Madison County,19121,2022-03-05T00:00:00.000,177.500,100.0,high
29227,1763475,Iowa,Adair County,19001,2022-02-26T00:00:00.000,0.000,100.0,high

In [15]:
print(cases_df.shape)
print(cases_df.dtypes)

(96660, 8)
index             int64
state_name       object
county_name      object
fips_code        object
date             object
cases           float64
test_percent    float64
severity         object
dtype: object